export const TID = {
  navLogo: "nav-logo",
  navLogin: "nav-login-btn",
  navRegister: "nav-register-btn",
  navLogout: "nav-logout-btn",
  navBrowse: "nav-browse-btn",
  navDashboard: "nav-dashboard-btn",
  navIntegrations: "nav-integrations-btn",
  landingGetStarted: "landing-get-started-btn",
  landingBrowseTalent: "landing-browse-talent-btn",
  loginEmail: "login-email",
  loginPassword: "login-password",
  loginSubmit: "login-submit-btn",
  registerName: "register-name",
  registerEmail: "register-email",
  registerPassword: "register-password",
  registerRoleTalent: "register-role-talent",
  registerRoleEmployer: "register-role-employer",
  registerSubmit: "register-submit-btn",
  profileHeadline: "profile-headline",
  profileBio: "profile-bio",
  profileSkills: "profile-skills",
  profileYears: "profile-years",
  profileLocation: "profile-location",
  profilePortfolio: "profile-portfolio",
  profileSuggestRate: "profile-suggest-rate-btn",
  profileHourlyRate: "profile-hourly-rate",
  profileSave: "profile-save-btn",
  browseSearch: "browse-search-input",
  browseSkill: "browse-skill-input",
  browseTalentCard: (id) => `browse-talent-card-${id}`,
  pkgCard: (id) => `pkg-card-${id}`,
  pkgBuy: (id) => `pkg-buy-${id}`,
  hireBtn: (id) => `hire-talent-${id}`,
  engagementRow: (id) => `engagement-row-${id}`,
  contractOpen: (id) => `contract-open-${id}`,
  contractSignature: "contract-signature-input",
  contractAgree: "contract-agree-checkbox",
  contractSubmit: "contract-submit-btn",
  integrationProviderCard: (id) => `integration-provider-${id}`,
  integrationToken: "integration-token-input",
  integrationWorkspace: "integration-workspace-input",
  integrationConnect: "integration-connect-btn",
  integrationSync: (id) => `integration-sync-${id}`,
  integrationDisconnect: (id) => `integration-disconnect-${id}`,
  workUpload: "work-upload-input",
  workUploadBtn: "work-upload-btn",
  navPricing: "nav-pricing-btn",
  navEoi: "nav-eoi-btn",
  navCalendar: "nav-calendar-btn",
  eoiMessage: "eoi-message",
  eoiHours: "eoi-hours",
  eoiEmployer: "eoi-employer-select",
  eoiSubmit: "eoi-submit-btn",
  eoiAccept: (id) => `eoi-accept-${id}`,
  eoiWithdraw: (id) => `eoi-withdraw-${id}`,
  eoiRow: (id) => `eoi-row-${id}`,
  availSlotAdd: "avail-slot-add-btn",
  availSlotDay: (i) => `avail-slot-day-${i}`,
  availSlotStart: (i) => `avail-slot-start-${i}`,
  availSlotEnd: (i) => `avail-slot-end-${i}`,
  availTimezone: "avail-timezone",
  availSave: "avail-save-btn",
};
